package vn.codezx.triviet.constants;

import jakarta.annotation.Nullable;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum MessageCode {
  MESSAGE_ERROR_SYSTEM_ERROR("TRI-VIET-500"), //
  MESSAGE_DUPLICATE("TRI-VIET-300"), //
  MESSAGE_NOT_FOUND("TRI-VIET-404"), //
  MESSAGE_ERROR_INPUT_ERROR("TRI-VIET-400"), //
  MESSAGE_UNAUTHORIZED_ERROR("TRI-VIET-401"), //
  MESSAGE_FORBIDDEN_ERROR("TRI-VIET-403"), //
  MESSAGE_CONFLICT_ERROR("TRI-VIET-409"), //
  MESSAGE_INVALID_EMAIL("TRI-VIET-501"), //
  MESSAGE_STU_CREATE_SUCCESS("STUDENT-CREATE-SUCCESS"), //
  MESSAGE_STU_CREATE_ERROR("STUDENT-CREATE-ERROR"), //
  MESSAGE_STU_DELETE_SUCCESS("STUDENT-DELETE-SUCCESS"), //
  MESSAGE_STU_DELETE_ERROR("STUDENT-DELETE-ERROR"), //
  MESSAGE_STU_UPDATE_SUCCESS("STUDENT-UPDATE-SUCCESS"), //
  MESSAGE_STU_UPDATE_ERROR("STUDENT-UPDATE-ERROR"), //
  MESSAGE_STU_GET_SUCCESS("STUDENT-GET-SUCCESS"), //
  MESSAGE_STU_NOT_FOUND("STUDENT-NOT-FOUND"), //
  MESSAGE_STU_EMAIL_EXISTED("STUDENT-EMAIL-EXISTED"), //
  MESSAGE_STU_EMAIL_INVALID("STUDENT-EMAIL-INVALID"), //
  MESSAGE_STU_PHONE_EXISTED("STUDENT-PHONE-EXISTED"), //
  MESSAGE_STU_PHONE_INVALID("STUDENT-PHONE-INVALID"), //
  MESSAGE_STU_ID_INVALID("STUNDENT-ID-INVALID"), //
  MESSAGE_FILE_NOT_FOUND("FILE-NOT-FOUND"), //
  MESSAGE_FILE_SERVE_ERROR("FILE-SERVE-ERROR"), //
  MESSAGE_DIS_CREATE_SUCCESS("DISCOUNT-CREATE-SUCCESS"), //
  MESSAGE_DIS_CREATE_ERROR("DISCOUNT-CREATE-ERROR"), //
  MESSAGE_DIS_NOT_FOUND("DISCOUNT-NOT-FOUND"), //
  MESSAGE_DIS_GET_SUCCESS("DISCOUNT-GET-SUCCESS"), //
  MESSAGE_DIS_UPDATE_SUCCESS("DISCOUNT-UPDATE-SUCCESS"), //
  MESSAGE_DIS_UPDATE_ERROR("DISCOUNT-UPDATE-ERROR"), //
  MESSAGE_DIS_DELETE_SUCCESS("DISCOUNT-DELETE-SUCCESS"), //
  MESSAGE_DIS_DELETE_ERROR("DISCOUNT-DELETE-ERROR"), //
  MESSAGE_EXPORT_SYSTEM_ERROR("EXPORT-SYSTEM-ERROR"), //
  MESSAGE_EXPORT_SUCCESS("EXPORT-SUCCESS"), //
  MESSAGE_SCHE_CREATE_ERROR("SCHE-CREATE-ERROR"), //
  MESSAGE_SCHE_CREATE_SUCCESS("SCHE-CREATE-SUCCESS"), //
  MESSAGE_SCHE_NOT_FOUND("SCHE-NOT-FOUND"), //
  MESSAGE_SCHE_GET_SUCCESS("SCHE-GET-SUCCESS"), //
  MESSAGE_SCHE_UPDATE_SUCCESS("SCHE-UPDATE-SUCCESS"), //
  MESSAGE_SCHE_UPDATE_ERROR("SCHE-UPDATE-ERROR"), //
  MESSAGE_LOC_CREATE_SUCCESS("LOC-CREATE-SUCCESS"), //
  MESSAGE_LOC_CREATE_ERROR("LOC-CREATE-ERROR"), //
  MESSAGE_LOC_NOT_FOUND("LOC-NOT-FOUND"), //
  MESSAGE_LOC_GET_SUCCESS("LOC-GET-SUCCESS"), //
  MESSAGE_LOC_UPDATE_SUCCESS("LOC-UPDATE-SUCCESS"), //
  MESSAGE_LOC_UPDATE_ERROR("LOC-UPDATE-ERROR"), //
  MESSAGE_LOC_DELETE_SUCCESS("LOC-DELETE-SUCCESS"), //
  MESSAGE_LOC_DELETE_ERROR("LOC-DELETE-ERROR"), //
  MESSAGE_CLASS_DAY_NOT_FOUND("CLASS-DAY-NOT-FOUND"), //
  MESSAGE_HOLI_NOT_FOUND("HOLI-NOT-FOUND"), //
  MESSAGE_STAFF_NOT_FOUND("STAFF-NOT-FOUND"), //
  MESSAGE_CLA_NAME_DULICATED("CLA-NAME-DUPLICATED"), //
  MESSAGE_CLA_NOTFOUND("CLA-NOT-FOUND"), //
  MESSAGE_GRA_NOT_FOUND("GRA-NOT-FOUND"), //
  MESSAGE_TES_NOT_FOUND("TES-NOT-FOUND"), //
  MESSAGE_FOR_NOT_FOUND("FOR-NOT-FOUND"), //
  MESSAGE_INVOICE_NOT_FOUND("INVOICE-NOT-FOUND"), //
  MESSAGE_INVOICE_DISCOUNT_INVALID("INVOICE-DISCOUNT_INVALID"), //
  MESSAGE_ENROLLMENT_NOT_FOUND("ENROLLMENT-NOT-FOUND"), //
  MESSAGE_ABS_NOTFOUND("ABS-NOT-FOUND"), //
  MESSAGE_LESS_TYPE_NOT_FOUND("LESS-TYPE-NOT-FOUND"); //


  private final String code;

  @Nullable
  public static MessageCode fromCode(String code) {
    for (MessageCode messageCode : MessageCode.values()) {
      if (messageCode.getCode().equals(code)) {
        return messageCode;
      }
    }
    return null;
  }
}
